cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:dish_id>', cart_add, name='cart_add'),
    path('remove/<int:dish_id>', cart_remove, name='cart_remove'),
]

gusto_cafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from gusto_cafe import settings
from account.views import register_view, login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main_gusto.urls")),
    path("admin-panel/", include("admin_gusto.urls")),
    path("register/", register_view, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path('cart/', include('cart.urls')),#
    path('orders/', include('orders.urls')),#
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_gusto/urls.py
from django.urls import path
from .views import main_page_view, dish_page_view

app_name = "main_gusto"

urlpatterns = [
    path("", main_page_view, name="main_page_view"),
    path("menu/dish/<int:id>/<slug:slug>", dish_page_view, name="dish_page_view"),
]

main_gusto/models.py
from django.db import models
from uuid import uuid4
from os import path
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    def get_file_name(self, filename):
        ext = filename.strip().split(".")[-1]
        filename = f"{uuid4()}.{ext}"
        return path.join("images/categories", filename)

    title = models.CharField(max_length=15, unique=True)
    photo = models.ImageField(upload_to=get_file_name)
    category_order = models.IntegerField(unique=True)
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.title}: {self.category_order}"

class Dish(models.Model):

    def get_file_name(self, filename):
        ext = filename.strip().split(".")[-1]  # Узнать разширение файла (my_photo.jpg -> [ "my_photo", "jpg" ])
        filename = f"{uuid4()}.{ext}"
        return path.join("images/dishes", filename)

    title = models.CharField(max_length=25, unique=True, db_index=True)
    slug = models.SlugField(db_index=True)
    photo = models.ImageField(upload_to=get_file_name)  # upload_to='products/%Y/%m/%d'
    dish_order = models.IntegerField()
    is_visible = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    available = models.BooleanField(default=True)
    desc = models.CharField(max_length=150, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta():
        ordering = ('title',)
        index_together = (('id', 'slug'),)

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.hiring)
    #     super(hire_article, self).save(*args, **kwargs) #Чтобы slug вводился автоматически и в формах.

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("main_gusto:dish_page_view", args=[self.id, self.slug])

class Info(models.Model):
    def get_file_name(self, filename):
        ext = filename.strip().split(".")[-1]  # Узнать разширение файла (my_photo.jpg -> [ "my_photo", "jpg" ])
        filename = f"{uuid4()}.{ext}"
        return path.join("images/info", filename)

    cafe_info = models.CharField(max_length=500, unique=True)
    photo = models.ImageField(upload_to=get_file_name)
    is_visible = models.BooleanField(default=True)

class Team(models.Model):
    def get_file_name(self, filename):
        ext = filename.strip().split(".")[-1]  # Узнать разширение файла (my_photo.jpg -> [ "my_photo", "jpg" ])
        filename = f"{uuid4()}.{ext}"
        return path.join("images/team", filename)

    team_info = models.CharField(max_length=500, unique=True)
    photo = models.ImageField(upload_to=get_file_name)
    is_visible = models.BooleanField(default=True)

class Phone(models.Model):
    phone = models.CharField(max_length=13, unique=True)
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.phone}"

class Adress(models.Model):
    city = models.CharField(max_length=20)
    street = models.CharField(max_length=20)
    home = models.CharField(max_length=5)
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.city}; {self.street}; {self.home}"

class OpeningHours(models.Model):
    day = models.CharField(max_length=10)
    hours_start = models.CharField(max_length=5)
    hours_end = models.CharField(max_length=5)

    def __str__(self):
        return f"{self.day} - {self.hours_start}-{self.hours_end}"

class CafeInfo(models.Model):
    adress_id = models.ForeignKey(Adress, on_delete=models.CASCADE)
    phone_id = models.ForeignKey(Phone, on_delete=models.CASCADE)
    openinghours_id = models.ForeignKey(OpeningHours, on_delete=models.CASCADE)


class Message(models.Model):
    user_name = models.CharField(max_length=40)
    user_email = models.EmailField()
    user_message = models.CharField(max_length=400)

    pub_date = models.DateField(auto_now_add=True)
    is_processed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user_name} : {self.user_email} : {self.user_message[:20]}"

main_gusto/forms.py
from django import forms
from .models import Message

class FormMessage(forms.ModelForm):
    user_name = forms.CharField(max_length=40,
                                widget=forms.TextInput(attrs={"type": "text", "id": "name", "class": "form-control",
                                                              "placeholder": "Имя", "required": "required"}))
    user_email = forms.EmailField(
        widget=forms.EmailInput(attrs={"type": "email", "id": "email", "class": "form-control",
                                       "placeholder": "Почта", "required": "required"}))
    user_message = forms.CharField(max_length=400,
                                   widget=forms.Textarea(
                                       attrs={"name": "message", "id": "message", "class": "form-control",
                                              "rows": "4", "placeholder": "Сообщение", "required": "required"}))

    class Meta():
        model = Message
        fields = ("user_name", "user_email", "user_message")

main_gusto/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import FormMessage
from cart.cart import Cart#

# Create your views here.
def main_page_view(request):

    if request.method == "POST":
        form = FormMessage(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")


    categories = Category.objects.filter(is_visible=True).order_by("category_order")
    for item in categories:
        dishes = Dish.objects.filter(category=item.pk).filter(is_visible=True).order_by("dish_order")
        item.dishes = dishes
    special = Dish.objects.filter(category__title="Меню от шефа")

    team_info = Team.objects.filter(is_visible=True)
    cafe_info = Info.objects.filter(is_visible=True)
    phone = Phone.objects.filter(is_visible=True)
    adress = Adress.objects.filter(is_visible=True)
    opening_hours = OpeningHours.objects.all()

    form = FormMessage()

    cart = Cart(request)#

    return render(request, "index.html", context={
        "categories": categories,
        "special": special,
        "team_info": team_info[0],
        "cafe_info": cafe_info[0],
        "phone": phone,
        "adress": adress,
        "opening_hours": opening_hours,
        "form": form,
        "cart": cart,#
    })


def dish_page_view(request, id, slug):
    dish = get_object_or_404(Dish, id=id, slug=slug)#, available=True)
    cart = Cart(request)
    return render(request, "dish_info.html", context={'dish': dish, 'cart': cart})#

main_gusto/templates/about.html
{% load static %}
<!-- About Section -->

<section id="about">
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-12 col-md-6">
              <img src={{ cafe_info.photo.url }} width="850px" alt="">
          </div>
          <div class="col-xs-12 col-md-3 col-md-offset-1">
            <div class="about-text">
              <div class="section-title">
                <h2>Описание кафе</h2>
              </div>
              <p>{{ cafe_info.cafe_info }}</p>
            </div>
          </div>
        </div>
      </div>
</section>

main_gusto/templates/contact.html
{% load static %}
<!-- Contact Section -->
<section id="contact" class="text-center">
      <div class="container text-center">
        <div class="col-md-4">
          <h3>Резервация</h3>
          <div class="contact-item">
            {% for one_phone in phone %}
                <p>{{ one_phone }}</p>
            {% endfor %}
          </div>
        </div>
        <div class="col-md-4">
          <h3>Адрес</h3>
          <div class="contact-item">
            {% for one_adress in adress %}
                <p>{{ one_adress }}</p>
            {% endfor %}
          </div>
        </div>
        <div class="col-md-4">
          <h3>Время работы</h3>
          <div class="contact-item">
            {% for time in opening_hours %}
                <p>{{ time }}</p>
            {% endfor %}
          </div>
        </div>
      </div>

      <div class="container">
        <div class="section-title text-center">
          <h3>Отправить сообщение</h3>
        </div>
        <div class="col-md-8 col-md-offset-2">
          <form name="sentMessage" id="contactForm" novalidate method="post">
              {% csrf_token %}
                <div class="row">
                  <div class="col-md-6">
                        <div class="form-group">
                          {{ form.user_name }}
{#                          <input type="text" id="name" class="form-control" placeholder="Name" required="required">#}
                          <p class="help-block text-danger"></p>
                        </div>
                  </div>
                      <div class="col-md-6">
                        <div class="form-group">
                            {{ form.user_email }}
{#                          <input type="email" id="email" class="form-control" placeholder="Email" required="required">#}
                          <p class="help-block text-danger"></p>
                        </div>
                      </div>
                </div>
                <div class="form-group">
                    {{ form.user_message }}
{#                  <textarea name="message" id="message" class="form-control" rows="4" placeholder="Message" required></textarea>#}
                  <p class="help-block text-danger"></p>
                </div>
                <div id="success"></div>
                <button type="submit" class="btn btn-custom btn-lg">Отправить сообщение</button>
          </form>
        </div>
      </div>
</section>

main_gusto/templates/dish_info.html
{% extends 'base.html' %}

{% block content %}


    <div class="container">
        <div id="row">
            <div class="col-md-4 col-md-offset-3">
                <h2>{{ dish.title }}</h2>
                <img src="/{{ dish.photo }}" width="500px" alt="">
                <p>{{ dish.desc }}</p>
            </div>
            <div class="col-md-6">
          </div>
        </div>
    </div>


{% endblock %}

main_gusto/templates/features.html
{% load static %}
<!-- Features Section -->
<section id="features" class="text-center">
      <div class="container">
        <div class="section-title">
          <h2>Меню от шефа</h2>
        </div>
        <div class="row">
              {% for dish in special %}
              <div class="col-xs-12 col-sm-4">
                <div class="features-item">

                  <h3><a href={{ dish.get_absolute_url }}>{{ dish.title }}</a></h3>

                  <a href={{ dish.get_absolute_url }}>
                      <img src={{ dish.photo }} class="img-responsive" alt="">
{#                    <img src="{% if dish.photo %}{{ dish.photo }}{% else %}{% static "img/no_photo.jpg" %}{% endif %}" class="img-responsive" alt="">#}
                  </a>

                  <a href={% url "cart:cart_add" dish.id %}>Купить</a>

                    <p>{{ dish.desc }}</p>
                </div>
              </div>
              {% endfor %}
        </div>
      </div>
</section>

main_gusto/templates/gallery.html
{% load static %}
<!-- Gallery Section -->
<section id="gallery">
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-6 col-md-3">
            <div class="gallery-item"> <img src={% static "img/gallery/01.jpg" %} class="img-responsive" alt=""></div>
          </div>
          <div class="col-xs-6 col-md-3">
            <div class="gallery-item"> <img src={% static "img/gallery/02.jpg" %} class="img-responsive" alt=""></div>
          </div>
          <div class="col-xs-6 col-md-3">
            <div class="gallery-item"> <img src={% static "img/gallery/03.jpg" %} class="img-responsive" alt=""></div>
          </div>
          <div class="col-xs-6 col-md-3">
            <div class="gallery-item"> <img src={% static "img/gallery/04.jpg" %} class="img-responsive" alt=""></div>
          </div>
        </div>
      </div>
</section>

main_gusto/templates/index.html
{% extends "base.html" %}
{% block content %}
    {% load static %}

    {% include "about.html" %}
    {% include "features.html" %}
    {% include "menu.html" %}
    {% include "gallery.html" %}
    {% include "team.html" %}
    {% include "contact.html" %}

{% endblock %}

main_gusto/templates/menu.html
{% load static %}<!-- Restaurant Menu Section -->
<section id="restaurant-menu">
      <div class="container">
          <div class="section-title text-center">
            <h2>Меню</h2>
          </div>
          <div class="row">
                  {% for category in categories %}
                  <div class="col-xs-12 col-sm-6">
                    <div class="menu-section">
                      <h2 class="menu-section-title">{{ category.title }}</h2>
                      {% for dish in category.dishes %}
                      <div class="menu-item">
                        <div class="menu-item-name">

                            <a href={{ dish.get_absolute_url }}>
                                {{ dish.title }}
                            </a>

                        <a href={% url "cart:cart_add" dish.id %}>Купить</a>

                        </div>
                        <div class="menu-item-price"> {{ dish.price }} грн. </div>
                        <div class="menu-item-description"> {{ dish.desc }} </div>
                      </div>
                      {% endfor %}
                    </div>
                  </div>
                {% endfor %}
          </div>
      </div>
</section>

main_gusto/templates/team.html
{% load static %}
<!-- Team Section -->
<section id="team">
      <div class="container">
        <div id="row">
          <div class="col-md-6">
            <div class="col-md-10 col-md-offset-1">
              <div class="section-title">
                <h2>Встречайте нашего шефа</h2>
              </div>
              <p>{{ team_info.team_info }}</p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="team-img"><img src={{ team_info.photo.url }} alt=""></div>
          </div>
        </div>
      </div>
</section>