cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:dish_id>', cart_add, name='cart_add'),
    path('remove/<int:dish_id>', cart_remove, name='cart_remove'),
]

gusto_cafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from gusto_cafe import settings
from account.views import register_view, login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main_gusto.urls")),
    path("admin-panel/", include("admin_gusto.urls")),
    path("register/", register_view, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path('cart/', include('cart.urls')),#
    path('orders/', include('orders.urls')),#
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_gusto/urls.py
from django.urls import path
from .views import main_page_view, dish_page_view

app_name = "main_gusto"

urlpatterns = [
    path("", main_page_view, name="main_page_view"),
    path("menu/dish/<int:id>/<slug:slug>", dish_page_view, name="dish_page_view"),
]

orders/urls.py
from django.urls import path

from .views import *

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET

from main_gusto.models import Dish

from .cart import Cart

# Create your views here.

@require_GET
def cart_add(request, dish_id):
    cart = Cart(request)
    dish = get_object_or_404(Dish, id=dish_id)
    cart.add(dish=dish, quantity=1)
    return redirect('cart:cart_detail')

def cart_remove(request, dish_id):
    cart = Cart(request)
    dish = get_object_or_404(Dish, id=dish_id)
    cart.remove(dish)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart_detail.html', {'cart': cart})

cart/templates/cart_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>В корзине</h1>
    <table>
        <tbody>
            {% for item in cart %}
                {% with dish=item.dish %}
                    <tr>
                        <td>
                            <a href={{ dish.get_absolute_url }}>
                                <img src="/{{ dish.photo }}" width="150px">
                            </a>
                        </td>
                        <td>
                            <p>{{ dish.title }}</p>
                            <p>{{ item.quantity }} x {{ item.price }} грн. = {{ item.total_price }} грн.</p>
                        </td>
                        <td>
                            <a href={% url "cart:cart_remove" dish.id %}>Удалить</a>
                        </td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>
                    К оплате
                </td>
                <td>
                </td>
                <td class="num">
                    {{ cart.get_total_price }} грн.
                </td>
            </tr> 
        </tbody>
    </table>
    <p class="text-right">
        <a href={% url "main_gusto:main_page_view" %}>Продолжить покупки</a>
        <a href={% url "orders:order_create" %}>Оформить заказ</a>
    </p>
{% endblock %}